#!/usr/bin/env bash
# This script will transfer a file from the client to a server
# The script will accept 4 parameters:
#	path to the file to be transferred
#	IP of server to transfer file to
#	username of scp
#	path to SSH private key that scp will use

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	PATH_TO_FILE=$1
	IP=$2
	USERNAME=$3
	PATH_TO_SSH_KEY=$4

	scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/
fi
