#!/usr/bin/env bash
# This script will redirect the /redirect_me page of nginx server
# redirection will be '301 Moved Permanently'
# Server will also be configured to update these changes


# update package lists
apt-get update

# install nginx
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# create default index file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# configure nginx to redirect /redirect_me to another page
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# restart nginx
service nginx start
