#!/usr/bin/env bash
# This script will setup a 404 error page in nginx server


# update package lists
apt-get update

# install nginx
apt-get -y install nginx

# configure nginx 404 webpage
echo "Hello World!" > index.html
mv index.html /var/www/html

echo "Ceci n'est pas une page" > 404.html
mv 404.html /var/www/html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
		}
}" > default

mv -f default /etc/nginx/sites-available/default

# restart nginx
service nginx start
