#!/usr/bin/env bash
# This script will setup a 404 error page in nginx server
# The 404 page will display 'Ceci n'est pas une page'

# update package lists
sudo apt-get update

# install nginx
sudo apt-get -y install nginx

# configure 404 page message
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx start
