#!/usr/bin/env bash
# This script will setup a 404 error page in nginx server
# The 404 page will display 'Ceci n'est pas une page'

# update package lists
sudo apt-get update

# install nginx
sudo apt-get -y install nginx

# configure 404 page message
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo 'Hello World!' > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

# restart nginx
service nginx restart
