#!/usr/bin/env bash
# This script will ping an address provided by a user five times
# If no address is provided: 
#   display `Usage: 5-is_the_host_on_the_network {IP_ADDRESS}

if [ "$#" -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
