#!/usr/bin/env bash
# This script will implement a solution to the fizzbuzz problem using bash

for (( i=1; i<=100; i++ ))
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
