#!/usr/bin/env bash
# This script will read from the /etc/passwd dir and return the 
# username 
# uid and 
# home directory path for the user

while read -r line
do
	echo "$line" | cut -d ':' -f 1,3,6
done</etc/passwd
