#!/usr/bin/env bash
# This script will print specific str output based on a specified iteration using while and case conditions

count=1
while [ $count -le 20 ]
do
	case $count in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo $count
			;;
	esac
	((count++))
done
