#!/usr/bin/env bash
# This script will check if a file exists and is a regular file or not

if [ -e school ]  # exists
then
	echo "school file exists"

	if [ -s school ]  # empty
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f school ]  # regular file
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
