#!/usr/bin/env bash
# This script will fix an Apache error running on a docker container
# The fixed error will now return a message "Hello Holberton"

# add localhost as default server name to apache2 config file
echo "ServerName localhost" >> /etc/apache2.conf

# start service
sudo service apache2 start
